title: notmoby.co.uk
description: Apps, engineering notes, release logs
theme: minima

url: "https://www.notmoby.co.uk"
baseurl: ""

permalink: /blog/:year/:month/:day/:title/

plugins:
  - jekyll-sitemap
  - jekyll-feed

minima:
  skin: auto

header_pages:
  - apps.md
  - blog.md
  - about.md